import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>UglyDaisy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque maiores
      perspiciatis, soluta quisquam incidunt a doloribus rerum aperiam sequi
      vitae eius voluptatibus earum vel itaque sed ipsum, doloremque ullam
      omnis!
    </>
  );
}
